[autoconnect]
enable = true
host = '192.168.1.215'
port = 43103

[render]
draw_shadows = false
fov = 90.0
shadowmapres = 2048
z_far = 512.0

[window]
fullscreen = false
height = 648
vsync = true
width = 1152
