# This is the world.toml file I want to have
# when the world format is implemented. The following
# values for now mean absolutley nothing and they
# are here just because I want something to look at
# while developing the world format.

[world]             # General world settings
height_b = 0        # Build & generation limit begin            (default = 0)
height_e = 8        # Build & generation limit end              (default = 8)
edge = 512          # Generation edge                           (default = 512)

[generator]         # World generator settings (dimensions TBA)
use = "vgen"        # Generator to use (modded generators TBA)
seed = 1234         # General seed for the generator
vgen_fseed = 1234   # Generator-specific setting 1
vgen_rx = 32        # Generator-specific setting 2

[spawn]             # Spawn area settings
distribute = true   # Use a random position within radius       (default = true)
base = [0, 0, 0]    # Base spawn coordinate (circle center)     (default = 0 0 0)
radius = 32         # Spawn area radius (if distribute = true)  (default = 32)
