// user.js is a user-defined configuration script.
// While init.js is auto-generated by the game,
// this file is usually left untouched and can be
// changed. You might change CVar values here, configure
// mods and addons and just straight up crash the game.
Log.info("Hello from server user.js");
Log.info("The server will listen on port ", CVar.get("net.port"));
